### PR TITLE
Enhance NVIDIA package management in spark-rapids.sh

### LINKED ISSUE #1321: GPU driver installation fails on dataproc 2.2-ubuntu22
**Error as seen in `dataproc-initialization-script-0_output`**

```
++ apt-get install -y -q --no-install-recommends nvidia-driver-550-open
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nvidia-driver-550-open : Depends: libnvidia-gl-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: nvidia-dkms-550-open (<= 550.54.15-1)
                          Depends: nvidia-dkms-550-open (>= 550.54.15)
                          Depends: nvidia-kernel-common-550 (<= 550.54.15-1) but it is not going to be installed
                          Depends: nvidia-kernel-common-550 (>= 550.54.15) but it is not going to be installed
                          Depends: nvidia-kernel-source-550-open (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: libnvidia-compute-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: libnvidia-extra-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: nvidia-compute-utils-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: libnvidia-decode-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: libnvidia-encode-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: nvidia-utils-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: libnvidia-cfg1-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
                          Depends: libnvidia-fbc1-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
 xserver-xorg-video-nvidia-550 : Depends: libnvidia-cfg1-550 (= 550.54.15-0ubuntu1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Reproduce:**

```
export REGION=us-central1
export GCS_BUCKET=
export CLUSTER_NAME=
export NUM_GPUS=1
export NUM_WORKERS=2

gcloud dataproc clusters create $CLUSTER_NAME  \
    --region=$REGION \
    --zone="" \
    --image-version=2.2-ubuntu22 \
    --temp-bucket=$GCS_BUCKET\
    --initialization-actions=gs://goog-dataproc-initialization-actions-${REGION}/spark-rapids/spark-rapids.sh \
    --master-machine-type=n1-standard-16 \
    --num-workers=$NUM_WORKERS \
    --worker-accelerator=type=nvidia-l4,count=$NUM_GPUS \
    --worker-machine-type=g2-standard-12 \
    --bucket=$GCS_BUCKET \
    --no-shielded-secure-boot \
    --enable-component-gateway \
    --subnet=default
```

@knoguchi22 identified that this works with **2.2.55-ubuntu22** but fails with **2.2.56-ubuntu22**.

Update:
The issue still persists with version `2.2.57-ubuntu22`, which is the latest release as of May 21, 2025.

### PR DESCRIPTION
**Pull request by SurajAralihalli**
Resolves #1321 

- Added `unhold_nvidia_packages` function to allow upgrades of NVIDIA packages.
- Updated `hold_nvidia_packages` function to suppress output during execution.
- Integrated `unhold_nvidia_packages` call in the `install_nvidia_gpu_driver` function to ensure packages can be upgraded as needed.

### CODE REVIEW

**Comment by SurajAralihalli** [comment]
@jayadeep-jayaraman pls help review, thanks!

**Review by cjac — APPROVED** [review]
LGTM

File: spark-rapids/spark-rapids.sh [hunk 1]
```diff
@@ -343,13 +343,19 @@ readonly NVIDIA_REPO_URL="${NVIDIA_BASE_DL_URL}/cuda/repos/${shortname}/x86_64"
 # Hold all NVIDIA-related packages from upgrading unintenionally or services like unattended-upgrades
 # Users should run apt-mark unhold before they wish to upgrade these packages
 function hold_nvidia_packages() {
-  apt-mark hold nvidia-*
-  apt-mark hold libnvidia-*
+  apt-mark hold nvidia-* > /dev/null 2>&1
```
Comment (cjac) [inline spark-rapids/spark-rapids.sh:346]: Yeah.  That can get noisy

File: spark-rapids/spark-rapids.sh [hunk 2]
```diff
@@ -402,6 +408,9 @@ function install_nvidia_gpu_driver() {
 
   elif is_ubuntu ; then
 
+    # Unhold NVIDIA packages to allow upgrades (see issue #1321)
+    unhold_nvidia_packages
+
     execute_with_retries "apt-get install -y -q 'linux-headers-$(uname -r)'"
```
Comment (cjac) [inline spark-rapids/spark-rapids.sh:414]: I still think that upgrading the kernel in an init action is folly, but the a100 still requires a reboot, so I'll allow it.  I've been talking with @jayadeep-jayaraman about a potential patch to the GPU attaching mechanism in GCE to allow a ,passthrough=true argument in addition to the type=...,count=... arguments so that we can simulate a UEFI PCIe devices reset using qemu without a reboot.

Better would be if NV could patch their driver so that nvidia-smi --reset worked for the a100s without requiring a reboot, be it simulated or real.

**Comment by cjac** [comment]
All tests passing!

File: spark-rapids/spark-rapids.sh (hunk 2 above)
Comment (SurajAralihalli) [reply spark-rapids/spark-rapids.sh:414]: I agree, thanks for checking @cjac!
