### PR TITLE
[prometheus] Fix Kafka agent download URI

### LINKED ISSUE #804: Initialization action for prometheus fails, because centra.maven.org no longer exists
Initialization action for prometheus fails, because it tried to download dependencies from domain that does not exists (central.maven.org). repo1.maven.org should work, also, it needs https, since 9m ago they started requiring https.

This is from error log:
```
+ wget -nv --timeout=30 --tries=5 --retry-connrefused http://central.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.11.0/jmx_prometheus_javaagent-0.11.0.jar -P /usr/lib/kafka/libs
wget: unable to resolve host address ‘central.maven.org’
```

https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/prometheus/prometheus.sh#L31

### PR DESCRIPTION
**Pull request by Gaurangi94**
Fixes #804

### CODE REVIEW

File: prometheus/prometheus.sh [hunk 1]
```diff
@@ -28,7 +28,7 @@ readonly KAFKA_CONFIG_FILE=${KAFKA_CONFIG_DIR}/server.properties
 readonly KAFKA_LIBS_DIR=/usr/lib/kafka/libs
 readonly KAFKA_JMX_JAVAAGENT_VERSION='0.11.0'
 readonly KAFKA_JMX_JAVAAGENT_NAME="jmx_prometheus_javaagent-${KAFKA_JMX_JAVAAGENT_VERSION}.jar"
-readonly KAFKA_JMX_JAVAAGENT_URI="http://central.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${KAFKA_JMX_JAVAAGENT_VERSION}/${KAFKA_JMX_JAVAAGENT_NAME}"
+readonly KAFKA_JMX_JAVAAGENT_URI="https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/${KAFKA_JMX_JAVAAGENT_VERSION}/${KAFKA_JMX_JAVAAGENT_NAME}"
```
Comment (Gaurangi94) [inline prometheus/prometheus.sh:31]: @medb I tested this script using the set-up listed here. Although the packages on this line are downloaded as expected, there was an error that said "kafka-server-start.sh" not found (line 134 in this file).

I tried adding kafka in initialization-actions but that did led to some issues with Zookeeper.

Since I have not used prometheus before, could you tell me if I am missing any set-up here?

Comment (medb) [reply prometheus/prometheus.sh:31]: I think that you need to create cluster with Kafka init action to test Prometheus integration w/ Kafka:
https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/kafka

Note, that you need to specify Kafka init action before Prometheus init action.

Comment (Gaurangi94) [reply prometheus/prometheus.sh:31]: I already tried that, but as mentioned it led to issues with zookeeper. Did zookeeper have to be included too?

Also can we update the init action steps listed [here](https://github.com/GoogleCloudDataproc/initialization-actions/tree/master/prometheus), since they do not work as is?

Comment (Gaurangi94) [reply prometheus/prometheus.sh:31]: Exception in thread "main" org.apache.zookeeper.KeeperException$ConnectionLossException: KeeperErrorCode = ConnectionLoss for /
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:102)
	at org.apache.zookeeper.KeeperException.create(KeeperException.java:54)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1541)
	at org.apache.zookeeper.ZooKeeper.getChildren(ZooKeeper.java:1569)
	at org.apache.zookeeper.ZooKeeperMain.processZKCmd(ZooKeeperMain.java:732)
	at org.apache.zookeeper.ZooKeeperMain.processCmd(ZooKeeperMain.java:600)
	at org.apache.zookeeper.ZooKeeperMain.run(ZooKeeperMain.java:363)
	at org.apache.zookeeper.ZooKeeperMain.main(ZooKeeperMain.java:291)
+ echo 'Failed to connect to ZooKeeper prometheus-3-m:2181, retry 10...'

Comment (Gaurangi94) [reply prometheus/prometheus.sh:31]: Resolved the issue by creating HA cluster. 

Maybe we should update init-actions instructions to avoid confusion?

File: prometheus/README.md [hunk 2]
```diff
@@ -14,7 +14,9 @@ You can use this initialization action to create a new Dataproc cluster with Pro
     CLUSTER_NAME=<cluster_name>
     gcloud dataproc clusters create ${CLUSTER_NAME} \
         --region ${REGION} \
-        --initialization-actions gs://goog-dataproc-initialization-actions-${REGION}/prometheus/prometheus.sh
+        --num-masters 3 \
```
Comment (medb) [inline prometheus/README.md:17]: Instead of using HA cluster you need to enable Zookeper explicitly for non-HA clusters: `--optioonal-components=ZOOKEEPER`

File: prometheus/README.md [hunk 3]
```diff
@@ -14,7 +14,9 @@ You can use this initialization action to create a new Dataproc cluster with Pro
...
+        --metadata "run-on-master=true" \
+        --initialization-actions gs://goog-dataproc-initialization-actions-${REGION}/kafka/kafka.sh,gs://goog-dataproc-initialization-actions-${REGION}/prometheus/prometheus.sh
```
Comment (medb) [inline prometheus/README.md:19]: I think we need example of 2 commands, w/ and w/o Kafka init action. If Kafka init action is not installed, then we should set metadata value to disable Prometheus integration w/ Kafka.

**Review by medb — CHANGES_REQUESTED** [review]

File: prometheus/README.md (hunk 3 above)
Comment (Gaurangi94) [reply prometheus/README.md:18]: Can we disable Prometheus integration with Kafka? From the init script it seems like Kafka is always used. Doesn't seem like there is a flag to disable it. Do you mean we should introduce a new metadata?

**Review by medb — CHANGES_REQUESTED** [review]

**Comment by Gaurangi94** [comment]
ERROR: Couldn't start the build. Unable to run tests
Step #8 - "dataproc-2.0-debian10-tests": ERROR: no such package 'prometheus': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package. - Build failure. 

Is this expected? I have not made any changes to a build file

**Review by medb — APPROVED** [review]
