### PR TITLE
[rapids]add image2.1 support for spark-rapids init script

### LINKED ISSUE #1043: spark-rapids init script does not work on image2.1
We use [spark-rapids init script](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/spark-rapids/spark-rapids.sh) to initialize image2.0 version cluster(such as --image-version=2.0-ubuntu18 \) which works well, and I used to test it with `--image-version=2.1.0-RC2-debian11` and `--image-version=2.1.0-RC2-ubuntu20 \` two months ago which also works.

But recently since the `2.1-ubuntu20` version release, the init script failed to initialize the image2.1 cluster(2.1-ubuntu20), from the log we found it is because yarn cannot find GPU resources, and` nvidia-smi` does not work. And the scripts could not work with `--image-version=2.1.0-RC2-debian11` or `--image-version=2.1.0-RC2-ubuntu20 \` now.

We tried to reboot the node but seems does not work, any idea about this?

### PR DESCRIPTION
**Pull request by nvliyuan**
This pr is to add image-v2.1 support for spark-rapids init script.

The update is following this [guide](https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#secure-boot)

fix #1043 
Signed-off-by: liyuan <yuali@nvidia.com>

### CODE REVIEW

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman, could you help review?
FYI @viadea

**Comment by nvliyuan** [comment]
image
image

verified in local

**Comment by nvliyuan** [comment]
@cjac could you help share the log?

**Comment by cjac** [comment]
I received the same error this time.  Not sure what might be causing the problem.

+ kubectl logs -f presubmit-1-5-rocky8-31dcbd99-2ac8-4a6e-af05-3ea83d52db19 --since-time=2023-02-09T02:14:52+00:00 --timestamps=true
Error from server: Get "https://10.128.0.68:10250/containerLogs/default/presubmit-1-5-rocky8-31dcbd99-2ac8-4a6e-af05-3ea83d52db19/presubmit-1-5-rocky8-31dcbd99-2ac8-4a6e-af05-3ea83d52db19?follow=true&sinceTime=2023-02-09T02%3A14%3A52Z&timestamps=true": tunnel closed

**Comment by cjac** [comment]
no, the first one was ubuntu and the second one was rocky.  Maybe it's happening for both, but it's a race to see which fails first?

**Comment by nvliyuan** [comment]
@cjac I just revert all changes, could you help build again to see if we still have errors?

**Comment by nvliyuan** [comment]
do we still hit the same error?

**Comment by nvliyuan** [comment]
seems the test failed with image1.5, the script drop the support for image1.5 because spark-rapids cannot work with spark2.*, skip the test

**Comment by nvliyuan** [comment]
@cjac could you help build again?

**Comment by cjac** [comment]
Fetched 104 MB in 56s (1863 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/libv/libvorbis/libvorbis0a_1.3.6-2ubuntu1_amd64.deb  Connection failed [IP: 185.125.190.39 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get update && apt-get install -y openjdk-8-jdk python3-setuptools bazel' returned a non-zero code: 100

**Comment by nvliyuan** [comment]
@cjac could you help share the log?

**Comment by cjac** [comment]
+ kubectl logs -f presubmit-2-0-debian10-8b375948-d759-457e-8c5c-1f3e0326de8c --since-time=2023-02-09T04:33:18+00:00 --timestamps=true
Error from server (NotFound): pods "presubmit-2-0-debian10-8b375948-d759-457e-8c5c-1f3e0326de8c" not found
+ [[ 1 != 0 ]]
+ kubectl describe pod/presubmit-2-0-debian10-8b375948-d759-457e-8c5c-1f3e0326de8c
Error from server (NotFound): pods "presubmit-2-0-debian10-8b375948-d759-457e-8c5c-1f3e0326de8c" not found

**Comment by cjac** [comment]
I'm going to call it a night.  I've handed off to engineers in APAC

**Comment by nvliyuan** [comment]
> I'm going to call it a night. I've handed off to engineers in APAC

Thanks @cjac, just revert to add the updates.

**Comment by viadea** [comment]
LGTM. Have we tested the MIG support as well on DP 2.1?

**Comment by nvliyuan** [comment]
all OS (Debian11 Rocky8 Ubuntu20) works well;
but MIG does not work, I can manually make it work, I am checking what is wrong with the script...

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman updated and make MIG work again, could you help build again?
FYI @viadea

File: spark-rapids/spark-rapids.sh [hunk 1]
```diff
@@ -180,23 +184,83 @@ function install_nvidia_gpu_driver() {
       "${NVIDIA_DEBIAN_CUDA_URL}" -o cuda.run
     bash "./cuda.run" --silent --toolkit --no-opengl-libs
   elif [[ ${OS_NAME} == ubuntu ]]; then
-    curl -fsSL --retry-connrefused --retry 3 --retry-max-time 5 \
+    
+    # we need to install additional modules with enabling secure boot, see issue: https://github.com/GoogleCloudDataproc/initialization-actions/issues/1043
+    # following [guide](https://cloud.google.com/compute/docs/gpus/install-drivers-gpu#secure-boot) for detailed information.
+    if [[ ${DATAPROC_IMAGE_VERSION} == 2.1 ]]; then
```
[the remark this answers is not in the document]
Comment (jayadeep-jayaraman) [reply spark-rapids/spark-rapids.sh]: Hi @nvliyuan - is this change done and do you want me to run the tests?

[the remark this answers is not in the document]
Comment (nvliyuan) [reply spark-rapids/spark-rapids.sh]: yes, already update to checking SECURE_BOOT

**Comment by nvliyuan** [comment]
Hi @cjac @jayadeep-jayaraman , could you help /gcbrun to see if we could pass the tests?

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , could you help share the error log?

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - there is an issue with the init scripts and I have raised a PR [here](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1049). Once it is merged I will re-trigger the tests

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman, I just fond the pr is merged, could you help trigger the tests?

**Comment by nvliyuan** [comment]
Hi @cjac , could you help share the log?

**Comment by cjac** [comment]
Sorry, I'm away from my laptop right now.  I'll be doing some development
in a few hours, though.  I'm in Thailand for a few weeks, so maybe our
schedules will overlap a bit more while I'm here.

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - only a portion of the PR (support for 2.1) is merged. The changes to handle K8S 1.24 is still in progress and I will raise a separate PR for it, once that change is done then I will trigger the test for this. Currently, all tests will fail with the below error
```
Step #7 - "dataproc-2.0-ubuntu18-tests": + kubectl run presubmit-2-0-ubuntu18-c604a348-3124-4995-9747-c1794de718ce --image=gcr.io/cloud-dataproc-ci/init-actions-image:c604a348-3124-4995-9747-c1794de718ce --requests=cpu=750m,memory=2Gi,ephemeral-storage=2Gi --restart=Never --env=COMMIT_SHA=fc4060dfdb2373b2d27894eb14314003917f9e7c --env=IMAGE_VERSION=2.0-ubuntu18 --command -- bash /init-actions/cloudbuild/presubmit.sh
Step #4 - "dataproc-1.5-ubuntu18-tests": Error: unknown flag: --requests
Step #4 - "dataproc-1.5-ubuntu18-tests": See 'kubectl run --help' for usage.
Step #6 - "dataproc-2.0-rocky8-tests": Error: unknown flag: --requests
Step #6 - "dataproc-2.0-rocky8-tests": See 'kubectl run --help' for usage.
Step #2 - "dataproc-1.5-debian10-tests": Error: unknown flag: --requests
Step #2 - "dataproc-1.5-debian10-tests": See 'kubectl run --help' for usage.
Step #7 - "dataproc-2.0-ubuntu18-tests": Error: unknown flag: --requests
Step #7 - "dataproc-2.0-ubuntu18-tests": See 'kubectl run --help' for usage.
Step #5 - "dataproc-2.0-debian10-tests": Error: unknown flag: --requests
Step #5 - "dataproc-2.0-debian10-tests": See 'kubectl run --help' for usage.
Step #3 - "dataproc-1.5-rocky8-tests": Error: unknown flag: --requests
Step #3 - "dataproc-1.5-rocky8-tests": See 'kubectl run --help' for usage.
```

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman, sure, thanks for the updates. Please help trigger the test if the PRs (support for 2.1) are merged.

**Comment by jayadeep-jayaraman** [comment]
Without the k8s changes we will not be able to test the 2.1 image. As soon as I am done with those changes, I will trigger this test.

**Comment by jayadeep-jayaraman** [comment]
Hi @cjac @nvliyuan - I have triggered the run to test the GPU related changes after the temporary change has been put in place. Will work on the permanent fix next week

**Comment by jayadeep-jayaraman** [comment]
Can you please resync your workspace and push the changes back so that I can trigger the test?

**Comment by nvliyuan** [comment]
> Can you please resync your workspace and push the changes back so that I can trigger the test?

Hi @jayadeep-jayaraman , do I need to push another commit?

**Comment by jayadeep-jayaraman** [comment]
It is still picking up the old vesion of the code `kubectl run presubmit-2-0-rocky8-53a6f1a7-ab1c-45d9-837f-48a87c470c5d --image=gcr.io/cloud-dataproc-ci/init-actions-image:53a6f1a7-ab1c-45d9-837f-48a87c470c5d --requests=cpu=750m,memory=2Gi,ephemeral-storage=2Gi`. Can you pls check

**Comment by nvliyuan** [comment]
@jayadeep-jayaraman merged the changes from master, could you help gbcrun again?

**Comment by jayadeep-jayaraman** [comment]
Thanks, I have triggered the tests and it is running now.

**Comment by jayadeep-jayaraman** [comment]
Here are some of the errors that I found, I also saw errors related to Debian 11. Can you please test the scripts once locally before we run the tests again ?

Rocky 8 , Dataproc 2.0
```
+ list kernel-headers-4.18.0-425.10.1.el8_7.x86_64
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: line 570: list: command not found
+ upgrade_kernel
+ [[ rocky == \d\e\b\i\a\n ]]
+ [[ rocky == \u\b\u\n\t\u ]]
+ [[ rocky == rocky ]]
++ yum info --installed kernel
++ awk '/^Version/ {print $3}'
+ KERN_VER=4.18.0
++ yum info --installed kernel
++ awk '/^Release/ {print $3}'
+ KERN_REL=425.10.1.el8_7
+ CURRENT_KERNEL_VERSION=4.18.0-425.10.1.el8_7
+ [[ rocky == \d\e\b\i\a\n ]]
+ [[ rocky == \u\b\u\n\t\u ]]
+ [[ rocky == \r\o\c\k\y ]]
+ yum info --available kernel
Last metadata expiration check: 0:00:03 ago on Wed 22 Feb 2023 04:46:43 AM UTC.
Available Packages
Name         : kernel
Version      : 4.18.0
Release      : 425.13.1.el8_7
Architecture : x86_64
Size         : 8.8 M
Source       : kernel-4.18.0-425.13.1.el8_7.src.rpm
Repository   : baseos
Summary      : The Linux kernel, based on version 4.18.0, heavily modified with backports
URL          : http://www.kernel.org/
License      : GPLv2 and Redistributable, no modification permitted
Description  : This is the package which provides the Linux kernel for Rocky
             : Linux. It is based on upstream Linux at version 4.18.0 and maintains kABI
             : compatibility of a set of approved symbols, however it is heavily modified with
             : backports and fixes pulled from newer upstream Linux kernel releases. This means
             : this is not a 4.18.0 kernel anymore: it includes several components which come
             : from newer upstream linux versions, while maintaining a well tested and stable
             : core. Some of the components/backports that may be pulled in are: changes like
             : updates to the core kernel (eg.: scheduler, cgroups, memory management, security
             : fixes and features), updates to block layer, supported filesystems, major driver
             : updates for supported hardware in Rocky Linux, enhancements for
             : enterprise customers, etc.

++ yum info --available kernel
++ awk '/^Version/ {print $3}'
+ KERN_VER=4.18.0
++ yum info --available kernel
++ awk '/^Release/ {print $3}'
Error: No matching Packages to list
+ KERN_REL=
```

**Comment by nvliyuan** [comment]
It is weird, the PR does not change anything with Rocky8-image2.0, I also double check again with debian11-image2.1 & Rocky8-image2.0 and the script works well.

**Comment by nvliyuan** [comment]
Just find that I test with `--no-shielded-secure-boot \` with Deibain11-img2.1, since there is no way to install GPU driver in Debian/Rocky with secure-boot, let me disable it in the script.
For Rocky8-image2.0 error, still need to investigate.

**Comment by nvliyuan** [comment]
Oh, sorry that just find my Rocky test script actually tests Debian, there is indeed an error to starting rocky cluster.

File: spark-rapids/spark-rapids.sh [hunk 2]
```diff
@@ -509,7 +567,7 @@ function upgrade_kernel() {
 function main() {
 
   if [[ "${OS_NAME}" == "rocky" ]]; then
-    if dnf list kernel-devel-$(uname -r) && list kernel-headers-$(uname -r); then
+    if dnf list kernel-devel-$(uname -r) && dnf list kernel-headers-$(uname -r); then
```
Comment (nvliyuan) [inline spark-rapids/spark-rapids.sh:570]: missing dnf command

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman @cjac , just fix the rocky8 issue, the root cause is that we miss a `dnf` command in a if clause, see this [link](https://github.com/GoogleCloudDataproc/initialization-actions/pull/1046#discussion_r1115433645)

for debian11-image2.1 issue and rocky8-image2.1 issue, can we test with no-secure-boot cluster in presubmit job? since we cannot disable it in scripts.

**Comment by nvliyuan** [comment]
I believe the test will still fail if the presubmit job test with debian/rocky OS with secure-boot enabled.

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - In the test scripts that are part of spark-rapids you can disable secure boot when you create debian and rocky clusters. I have executed the tests and will let you know if all versions pass except 2.1 debian and rocky

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - for Debian 2.0 I am seeing the below errors, in addition can you fix the test script to disable secure boot if it is 2.1 image and os is rocky or debian. Once the changes are made I will rerun the tests.

```
2023-02-24T04:05:32.520246911Z FAIL: //:test_spark_rapids (shard 1 of 3) (see /home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test_spark_rapids/shard_1_of_3/test_attempts/attempt_1.log)
2023-02-24T04:18:41.755757811Z FAIL: //:test_spark_rapids (shard 1 of 3) (see /home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test_spark_rapids/shard_1_of_3/test_attempts/attempt_2.log)
2023-02-24T04:31:49.424686260Z FAIL: //:test_spark_rapids (shard 1 of 3) (see /home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test_spark_rapids/shard_1_of_3/test.log)
2023-02-24T04:31:49.430601724Z 
2023-02-24T04:31:49.430669921Z FAILED: //:test_spark_rapids (Summary)
2023-02-24T04:31:49.430687159Z       /home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test_spark_rapids/shard_1_of_3/test.log
2023-02-24T04:31:49.430699788Z       /home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test_spark_rapids/shard_1_of_3/test_attempts/attempt_1.log
2023-02-24T04:31:49.430708537Z       /home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/testlogs/test_spark_rapids/shard_1_of_3/test_attempts/attempt_2.log
2023-02-24T04:31:49.451258846Z INFO: From Testing //:test_spark_rapids (shard 1 of 3):
2023-02-24T04:31:49.657027749Z ==================== Test output for //:test_spark_rapids (shard 1 of 3):
2023-02-24T04:31:49.657090578Z Running tests under Python 3.8.10: /usr/bin/python3
2023-02-24T04:31:49.657106123Z [ RUN      ] SparkRapidsTestCase.test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b')
2023-02-24T04:31:49.657119552Z [  FAILED  ] SparkRapidsTestCase.test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b')
2023-02-24T04:31:49.657128352Z [ RUN      ] SparkRapidsTestCase.test_spark_rapids('STANDARD', ['w-0'], 'type=nvidia-tesla-t4')
2023-02-24T04:31:49.657135632Z [       OK ] SparkRapidsTestCase.test_spark_rapids('STANDARD', ['w-0'], 'type=nvidia-tesla-t4')
2023-02-24T04:31:49.657142734Z ======================================================================
2023-02-24T04:31:49.657149910Z FAIL: test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b') (__main__.SparkRapidsTestCase)
2023-02-24T04:31:49.657157284Z test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b') (__main__.SparkRapidsTestCase)
2023-02-24T04:31:49.657165543Z test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b')
2023-02-24T04:31:49.657172943Z ----------------------------------------------------------------------
2023-02-24T04:31:49.657180583Z Traceback (most recent call last):
2023-02-24T04:31:49.657190247Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2023-02-24T04:31:49.657197690Z     test_method(self, *testcase_params)
2023-02-24T04:31:49.657205073Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 115, in test_install_gpu_with_mig
2023-02-24T04:31:49.657212563Z     self.verify_mig_instance("{}-{}".format(self.getClusterName(),
2023-02-24T04:31:49.657219680Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 23, in verify_mig_instance
2023-02-24T04:31:49.657247304Z     self.assert_instance_command(name,
2023-02-24T04:31:49.657256197Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 270, in assert_instance_command
2023-02-24T04:31:49.657263735Z     ret_code, stdout, stderr = self.assert_command(
2023-02-24T04:31:49.657271057Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2023-02-24T04:31:49.657279732Z     self.assertEqual(
2023-02-24T04:31:49.657287211Z AssertionError: 123 != 0 : Failed to execute command:
2023-02-24T04:31:49.657308176Z gcloud compute ssh test-rapids-standard-2-0-20230224-035249-u58m-w-0 --zone=us-central1-b --command="/usr/bin/nvidia-smi --query-gpu=mig.mode.current --format=csv,noheader | uniq | xargs -I % test % = 'Enabled'"
2023-02-24T04:31:49.657316269Z STDOUT:
2023-02-24T04:31:49.657323326Z 
2023-02-24T04:31:49.657330920Z STDERR:
2023-02-24T04:31:49.657338150Z 
2023-02-24T04:31:49.657344687Z 
2023-02-24T04:31:49.657351815Z ----------------------------------------------------------------------
2023-02-24T04:31:49.657358881Z Ran 2 tests in 841.875s
2023-02-24T04:31:49.657365794Z 
2023-02-24T04:31:49.657372680Z FAILED (failures=1)
2023-02-24T04:31:49.657379703Z ================================================================================
2023-02-24T04:31:49.657387154Z ==================== Test output for //:test_spark_rapids (shard 1 of 3):
2023-02-24T04:31:49.657394358Z Running tests under Python 3.8.10: /usr/bin/python3
2023-02-24T04:31:49.657402162Z [ RUN      ] SparkRapidsTestCase.test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b')
2023-02-24T04:31:49.657409643Z [  FAILED  ] SparkRapidsTestCase.test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b')
2023-02-24T04:31:49.657417067Z [ RUN      ] SparkRapidsTestCase.test_spark_rapids('STANDARD', ['w-0'], 'type=nvidia-tesla-t4')
2023-02-24T04:31:49.657424298Z [       OK ] SparkRapidsTestCase.test_spark_rapids('STANDARD', ['w-0'], 'type=nvidia-tesla-t4')
2023-02-24T04:31:49.657431506Z ======================================================================
2023-02-24T04:31:49.657438722Z FAIL: test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b') (__main__.SparkRapidsTestCase)
2023-02-24T04:31:49.657453866Z test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b') (__main__.SparkRapidsTestCase)
2023-02-24T04:31:49.657461509Z test_install_gpu_with_mig('STANDARD', ['m', 'w-0', 'w-1'], None, 'type=nvidia-tesla-a100', 'NVIDIA', 'us-central1-b')
2023-02-24T04:31:49.657468711Z ----------------------------------------------------------------------
2023-02-24T04:31:49.657476066Z Traceback (most recent call last):
2023-02-24T04:31:49.657482812Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2023-02-24T04:31:49.657489541Z     test_method(self, *testcase_params)
2023-02-24T04:31:49.657496450Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 115, in test_install_gpu_with_mig
2023-02-24T04:31:49.657513739Z     self.verify_mig_instance("{}-{}".format(self.getClusterName(),
2023-02-24T04:31:49.657537958Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 23, in verify_mig_instance
2023-02-24T04:31:49.657548424Z     self.assert_instance_command(name,
2023-02-24T04:31:49.657555981Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 270, in assert_instance_command
2023-02-24T04:31:49.657562911Z     ret_code, stdout, stderr = self.assert_command(
2023-02-24T04:31:49.657570167Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2023-02-24T04:31:49.657578755Z     self.assertEqual(
2023-02-24T04:31:49.657586719Z AssertionError: 123 != 0 : Failed to execute command:
2023-02-24T04:31:49.657594228Z gcloud compute ssh test-rapids-standard-2-0-20230224-040554-e2ac-w-0 --zone=us-central1-b --command="/usr/bin/nvidia-smi --query-gpu=mig.mode.current --format=csv,noheader | uniq | xargs -I % test % = 'Enabled'"
2023-02-24T04:31:49.657601520Z STDOUT:
```

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman @cjac ,just fix the mig script issue, and bazel tests passed in my local. But I don't know how to disable secure-boot in my test script, I try some config but none of them works. How can I disable it?

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , just update the test script to disable secure boot when OS is rocky and debian, it works in my local bazel test, could you help gcbrun?

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - due to changes in `integration_tests/dataproc_test_case.py` all the test cases are failing. For the time being can you revert the change made to this file and in the rapids test case can you bypass the 2.1 test for Debian and Rocky so that we can test the GPU related changes only. Once the tests are successful we can test for 2.1 debian and rocky separately. I will raise a separate request for fixing the other test scripts

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , sure, revert the changes and skip the tests for image2.1-debian and rocky.

**Comment by nvliyuan** [comment]
> The test is failing for mig. Can you pls check

Hi @jayadeep-jayaraman , I verified the MIG script works in my tests, I hit this issue if I did not set up the MIG script in `startup-script-url`, I am not sure whether the MIG script exists in [`self.INIT_ACTIONS_REPO`](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/integration_tests/dataproc_test_case.py#L121-L124), could you help verify?

**Comment by jayadeep-jayaraman** [comment]
Yes, you are right the mig.sh file is not present. I found one more interesting thing, in the gpu folder there is a [BUILD](https://github.com/GoogleCloudDataproc/initialization-actions/blob/e7605d720dc2989827c76ba7b7a9a929a546d8de/gpu/BUILD#L3) but it is not present inside spark-rapids folder. Can you add this ?

**Comment by nvliyuan** [comment]
add the BUILD script

**Comment by jayadeep-jayaraman** [comment]
The job is failing with the error

```
2023-03-01T13:54:42.374674679Z ERROR: /init-actions/BUILD:113:8: Label '//:spark-rapids/verify_xgboost_spark_rapids.scala' is invalid because 'spark-rapids' is a subpackage; perhaps you meant to put the colon here: '//spark-rapids:verify_xgboost_spark_rapids.scala'?
2023-03-01T13:54:42.471516443Z ERROR: /init-actions/BUILD:113:8: Label '//:spark-rapids/spark-rapids.sh' is invalid because 'spark-rapids' is a subpackage; perhaps you meant to put the colon here: '//spark-rapids:spark-rapids.sh'?
2023-03-01T13:54:42.471657517Z ERROR: /init-actions/BUILD:113:8: Label '//:spark-rapids/test_spark_rapids.py' is invalid because 'spark-rapids' is a subpackage; perhaps you meant to put the colon here: '//spark-rapids:test_spark_rapids.py'?
2023-03-01T13:54:42.571549028Z ERROR: Error evaluating ':test_spark_rapids': error loading package '': Package '' contains errors
2023-03-01T13:54:42.774154598Z INFO: Elapsed time: 26.779s
```


which looks like is coming from this [piece of code](https://github.com/GoogleCloudDataproc/initialization-actions/blob/84033d972e91b206e36091946f9074bc80c648ff/BUILD#LL113-L127C2). I checked for gpu and this logic is not present in this BUILD file, therefore can we remove this from here as we have a separate build file

In addition can we change `:test_spark_rapids` to `//spark-rapids:test_spark_rapids` present [here](https://github.com/GoogleCloudDataproc/initialization-actions/blob/84033d972e91b206e36091946f9074bc80c648ff/BUILD#LL11C11-L11C28)

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , just updated the BUILD scripts

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan apologies for going back and forth on this but the builds are failing because the folder has a dash in its name "spark-rapids" as per the logic defined [here](https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/cloudbuild/presubmit.sh#L88-L92) and below is the log:-

```
2023-03-01T16:46:41.921597834Z Starting local Bazel server and connecting to it...
2023-03-01T16:46:59.172345959Z ERROR: no such target '//:test_spark_rapids': target 'test_spark_rapids' not declared in package '' defined by /init-actions/BUILD (Tip: use `query "//:*"` to see all the targets in that package)
2023-03-01T16:46:59.409600905Z INFO: Elapsed time: 24.237s
```

I believe we will have to keep the tests in the top level BUILD file like it was there originally and remove BUILD file from spark-rapids folder. In the original BUILD file can you add mig.sh in the data variable inside py_tests. From [the documentation](https://bazel.build/reference/be/common-definitions#typical.data) all the files needed at runtime needs to be specified here

**Comment by nvliyuan** [comment]
Hi @jayadeep-jayaraman , just updated the BUILD scripts as suggested, thanks for the document, will read it tomorrow

**Comment by jayadeep-jayaraman** [comment]
With the latest changes 1.5 all version, 2.0 debian, 2.0 ubuntu and 2.1 debian and 2.0 rocky are passing the tests.

2.1 Ubuntu and 2.0 Rocky tests are failing with the below errors

2.0 Rocky Errors
```
+ grep -q NVIDIA
+ /usr/bin/nvidia-smi --query-gpu=mig.mode.current --format=csv,noheader
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: line 450: /usr/bin/nvidia-smi: No such file or directory
+ uniq
+ wc -l

+ return 0
+ modprobe nvidia
modprobe: FATAL: Module nvidia not found in directory /lib/modules/4.18.0-425.10.1.el8_7.x86_64
```

2.1 Ubuntu Errors
```
2023-03-02T01:22:07.430622044Z ================================================================================
2023-03-02T01:22:07.430629365Z ==================== Test output for //:test_spark_rapids (shard 3 of 3):
2023-03-02T01:22:07.430636546Z Running tests under Python 3.8.10: /usr/bin/python3
2023-03-02T01:22:07.430643280Z [ RUN      ] SparkRapidsTestCase.test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430650150Z [  FAILED  ] SparkRapidsTestCase.test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430673695Z ======================================================================
2023-03-02T01:22:07.430683490Z FAIL: test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4') (__main__.SparkRapidsTestCase)
2023-03-02T01:22:07.430690221Z test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4') (__main__.SparkRapidsTestCase)
2023-03-02T01:22:07.430696545Z test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430703008Z ----------------------------------------------------------------------
2023-03-02T01:22:07.430709852Z Traceback (most recent call last):
2023-03-02T01:22:07.430719756Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2023-03-02T01:22:07.430728165Z     test_method(self, *testcase_params)
2023-03-02T01:22:07.430735299Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 54, in test_spark_rapids
2023-03-02T01:22:07.431272227Z     self.createCluster(
2023-03-02T01:22:07.431383383Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 170, in createCluster
2023-03-02T01:22:07.431398478Z     _, stdout, _ = self.assert_command(
2023-03-02T01:22:07.431421886Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2023-03-02T01:22:07.431429181Z     self.assertEqual(
2023-03-02T01:22:07.431440290Z AssertionError: 1 != 0 : Failed to execute command:
2023-03-02T01:22:07.431448974Z gcloud dataproc clusters create test-rapids-single-2-1-20230302-011509-c9da --single-node --image-version=2.1-ubuntu20 --initialization-actions='gs://dataproc-init-actions-test-cloud-dataproc-ci/20230302-011459-jdpw/spark-rapids/spark-rapids.sh' --initialization-action-timeout=30m --metadata=gpu-driver-provider=NVIDIA,rapids-runtime=SPARK --master-accelerator=type=nvidia-tesla-t4 --worker-accelerator=type=nvidia-tesla-t4 --master-machine-type=n1-standard-4 --worker-machine-type=n1-standard-4 --master-boot-disk-size=1024GB --worker-boot-disk-size=1024GB --format=json --region=us-central1 --max-age=2h
2023-03-02T01:22:07.431469664Z STDOUT:
2023-03-02T01:22:07.431476283Z 
2023-03-02T01:22:07.431483031Z STDERR:
2023-03-02T01:22:07.431507604Z Waiting on operation [projects/cloud-dataproc-ci/regions/us-central1/operations/57c2b140-af85-3ec5-a85c-c66e17d71daa].
2023-03-02T01:22:07.431516544Z Waiting for cluster creation operation...
2023-03-02T01:22:07.434144284Z WARNING: Permissions are missing for the default service account '786080889824-compute@developer.gserviceaccount.com', missing permissions: [storage.objects.get, storage.objects.update] on the staging_bucket 'projects/_/buckets/dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1'. This usually happens when a custom resource (ex: custom staging bucket) or a user-managed VM Service account has been provided and the default/user-managed service account hasn't been granted enough permissions on the resource. See https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#VM_service_account.
2023-03-02T01:22:07.434177968Z WARNING: Permissions are missing for the default service account '786080889824-compute@developer.gserviceaccount.com', missing permissions: [storage.objects.get, storage.objects.update] on the temp_bucket 'projects/_/buckets/dataproc-temp-us-central1-786080889824-65know3v'. This usually happens when a custom resource (ex: custom staging bucket) or a user-managed VM Service account has been provided and the default/user-managed service account hasn't been granted enough permissions on the resource. See https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#VM_service_account.
2023-03-02T01:22:07.434191277Z ...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
2023-03-02T01:22:07.434200065Z ERROR: (gcloud.dataproc.clusters.create) Operation [projects/cloud-dataproc-ci/regions/us-central1/operations/57c2b140-af85-3ec5-a85c-c66e17d71daa] failed: Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20230302-011459-jdpw/spark-rapids/spark-rapids.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/12c7fb12-07bc-4364-9e0a-d7c2013bd994/test-rapids-single-2-1-20230302-011509-c9da-m/dataproc-initialization-script-0_output.
2023-03-02T01:22:07.434264584Z 
2023-03-02T01:22:07.430622044Z ================================================================================
2023-03-02T01:22:07.430629365Z ==================== Test output for //:test_spark_rapids (shard 3 of 3):
2023-03-02T01:22:07.430636546Z Running tests under Python 3.8.10: /usr/bin/python3
2023-03-02T01:22:07.430643280Z [ RUN      ] SparkRapidsTestCase.test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430650150Z [  FAILED  ] SparkRapidsTestCase.test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430673695Z ======================================================================
2023-03-02T01:22:07.430683490Z FAIL: test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4') (__main__.SparkRapidsTestCase)
2023-03-02T01:22:07.430690221Z test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4') (__main__.SparkRapidsTestCase)
2023-03-02T01:22:07.430696545Z test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430703008Z ----------------------------------------------------------------------
2023-03-02T01:22:07.430709852Z Traceback (most recent call last):
2023-03-02T01:22:07.430719756Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2023-03-02T01:22:07.430728165Z     test_method(self, *testcase_params)
2023-03-02T01:22:07.430735299Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 54, in test_spark_rapids
2023-03-02T01:22:07.431272227Z     self.createCluster(
2023-03-02T01:22:07.431383383Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 170, in createCluster
2023-03-02T01:22:07.431398478Z     _, stdout, _ = self.assert_command(
2023-03-02T01:22:07.431421886Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2023-03-02T01:22:07.431429181Z     self.assertEqual(
2023-03-02T01:22:07.431440290Z AssertionError: 1 != 0 : Failed to execute command:
2023-03-02T01:22:07.431448974Z gcloud dataproc clusters create test-rapids-single-2-1-20230302-011509-c9da --single-node --image-version=2.1-ubuntu20 --initialization-actions='gs://dataproc-init-actions-test-cloud-dataproc-ci/20230302-011459-jdpw/spark-rapids/spark-rapids.sh' --initialization-action-timeout=30m --metadata=gpu-driver-provider=NVIDIA,rapids-runtime=SPARK --master-accelerator=type=nvidia-tesla-t4 --worker-accelerator=type=nvidia-tesla-t4 --master-machine-type=n1-standard-4 --worker-machine-type=n1-standard-4 --master-boot-disk-size=1024GB --worker-boot-disk-size=1024GB --format=json --region=us-central1 --max-age=2h
2023-03-02T01:22:07.431469664Z STDOUT:
2023-03-02T01:22:07.431476283Z 
2023-03-02T01:22:07.431483031Z STDERR:
2023-03-02T01:22:07.431507604Z Waiting on operation [projects/cloud-dataproc-ci/regions/us-central1/operations/57c2b140-af85-3ec5-a85c-c66e17d71daa].
2023-03-02T01:22:07.431516544Z Waiting for cluster creation operation...
2023-03-02T01:22:07.434144284Z WARNING: Permissions are missing for the default service account '786080889824-compute@developer.gserviceaccount.com', missing permissions: [storage.objects.get, storage.objects.update] on the staging_bucket 'projects/_/buckets/dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1'. This usually happens when a custom resource (ex: custom staging bucket) or a user-managed VM Service account has been provided and the default/user-managed service account hasn't been granted enough permissions on the resource. See https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#VM_service_account.
2023-03-02T01:22:07.434177968Z WARNING: Permissions are missing for the default service account '786080889824-compute@developer.gserviceaccount.com', missing permissions: [storage.objects.get, storage.objects.update] on the temp_bucket 'projects/_/buckets/dataproc-temp-us-central1-786080889824-65know3v'. This usually happens when a custom resource (ex: custom staging bucket) or a user-managed VM Service account has been provided and the default/user-managed service account hasn't been granted enough permissions on the resource. See https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#VM_service_account.
2023-03-02T01:22:07.434191277Z ...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................done.
2023-03-02T01:22:07.434200065Z ERROR: (gcloud.dataproc.clusters.create) Operation [projects/cloud-dataproc-ci/regions/us-central1/operations/57c2b140-af85-3ec5-a85c-c66e17d71daa] failed: Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20230302-011459-jdpw/spark-rapids/spark-rapids.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/12c7fb12-07bc-4364-9e0a-d7c2013bd994/test-rapids-single-2-1-20230302-011509-c9da-m/dataproc-initialization-script-0_output.
2023-03-02T01:22:07.434264584Z 2023-03-02T01:22:07.430622044Z ================================================================================
2023-03-02T01:22:07.430629365Z ==================== Test output for //:test_spark_rapids (shard 3 of 3):
2023-03-02T01:22:07.430636546Z Running tests under Python 3.8.10: /usr/bin/python3
2023-03-02T01:22:07.430643280Z [ RUN      ] SparkRapidsTestCase.test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430650150Z [  FAILED  ] SparkRapidsTestCase.test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430673695Z ======================================================================
2023-03-02T01:22:07.430683490Z FAIL: test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4') (__main__.SparkRapidsTestCase)
2023-03-02T01:22:07.430690221Z test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4') (__main__.SparkRapidsTestCase)
2023-03-02T01:22:07.430696545Z test_spark_rapids('SINGLE', ['m'], 'type=nvidia-tesla-t4')
2023-03-02T01:22:07.430703008Z ----------------------------------------------------------------------
2023-03-02T01:22:07.430709852Z Traceback (most recent call last):
2023-03-02T01:22:07.430719756Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/io_abseil_py/absl/testing/parameterized.py", line 265, in bound_param_test
2023-03-02T01:22:07.430728165Z     test_method(self, *testcase_params)
2023-03-02T01:22:07.430735299Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/spark-rapids/test_spark_rapids.py", line 54, in test_spark_rapids
2023-03-02T01:22:07.431272227Z     self.createCluster(
2023-03-02T01:22:07.431383383Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 170, in createCluster
2023-03-02T01:22:07.431398478Z     _, stdout, _ = self.assert_command(
2023-03-02T01:22:07.431421886Z   File "/home/ia-tests/.cache/bazel/_bazel_ia-tests/83b1ae36bb04ea5432b9efccee83c25f/execroot/__main__/bazel-out/k8-fastbuild/bin/test_spark_rapids.runfiles/__main__/integration_tests/dataproc_test_case.py", line 322, in assert_command
2023-03-02T01:22:07.431429181Z     self.assertEqual(
2023-03-02T01:22:07.431440290Z AssertionError: 1 != 0 : Failed to execute command:
2023-03-02T01:22:07.431448974Z gcloud dataproc clusters create test-rapids-single-2-1-20230302-011509-c9da --single-node --image-version=2.1-ubuntu20 --initialization-actions='gs://dataproc-init-actions-test-cloud-dataproc-ci/20230302-011459-jdpw/spark-rapids/spark-rapids.sh' --initialization-action-timeout=30m --metadata=gpu-driver-provider=NVIDIA,rapids-runtime=SPARK --master-accelerator=type=nvidia-tesla-t4 --worker-accelerator=type=nvidia-tesla-t4 --master-machine-type=n1-standard-4 --worker-machine-type=n1-standard-4 --master-boot-disk-size=1024GB --worker-boot-disk-size=1024GB --format=json --region=us-central1 --max-age=2h
2023-03-02T01:22:07.431469664Z STDOUT:
2023-03-02T01:22:07.431476283Z 
2023-03-02T01:22:07.431483031Z STDERR:
2023-03-02T01:22:07.431507604Z Waiting on operation [projects/cloud-dataproc-ci/regions/us-central1/operations/57c2b140-af85-3ec5-a85c-c66e17d71daa].
2023-03-02T01:22:07.431516544Z Waiting for cluster creation operation...
2023-03-02T01:22:07.434144284Z WARNING: Permissions are missing for the default service account '786080889824-compute@developer.gserviceaccount.com', missing permissions: [storage.objects.get, storage.objects.update] on the staging_bucket 'projects/_/buckets/dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1'. This usually happens when a custom resource (ex: custom staging bucket) or a user-managed VM Service account has been provided and the default/user-managed service account hasn't been granted enough permissions on the resource. See https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#VM_service_account.
2023-03-02T01:22:07.434177968Z WARNING: Permissions are missing for the default service account '786080889824-compute@developer.gserviceaccount.com', missing permissions: [storage.objects.get, storage.objects.update] on the temp_bucket 'projects/_/buckets/dataproc-temp-us-central1-786080889824-65know3v'. This usually happens when a custom resource (ex: custom staging bucket) or a user-managed VM Service account has been provided and the default/user-managed service account hasn't been granted enough permissions on the resource. See https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/service-accounts#VM_service_account.
2023-03-02T01:22:07.434191277Z  done.
2023-03-02T01:22:07.434200065Z ERROR: (gcloud.dataproc.clusters.create) Operation [projects/cloud-dataproc-ci/regions/us-central1/operations/57c2b140-af85-3ec5-a85c-c66e17d71daa] failed: Initialization action failed. Failed action 'gs://dataproc-init-actions-test-cloud-dataproc-ci/20230302-011459-jdpw/spark-rapids/spark-rapids.sh', see output in: gs://dataproc-108de5de-43c2-4a4b-979a-adebc15a58a8-us-central1/google-cloud-dataproc-metainfo/12c7fb12-07bc-4364-9e0a-d7c2013bd994/test-rapids-single-2-1-20230302-011509-c9da-m/dataproc-initialization-script-0_output.
2023-03-02T01:22:07.434264584Z 
```

I looked at the log file and found the below as the last 10 lines
```
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  python3-software-properties
The following packages will be upgraded:
  python3-software-properties software-properties-common
2 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Need to get 32.0 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Abort.
```

**Comment by jayadeep-jayaraman** [comment]
Also found this in the 2.1 ubuntu logs, not sure if this is helpful

```
+ bdconfig set_property --configuration_file /etc/hadoop/conf/yarn-site.xml --name yarn.resource-types --value yarn.io/gpu --clobber
+ lspci
+ grep -q NVIDIA
+ /usr/bin/nvidia-smi --query-gpu=mig.mode.current --format=csv,noheader
+ uniq
/etc/google-dataproc/startup-scripts/dataproc-initialization-script-0: line 450: /usr/bin/nvidia-smi: No such file or directory
+ wc -l
0
+ [[ ubuntu == debian ]]
+ [[ ubuntu == ubuntu ]]
++ uname -r
+ execute_with_retries 'apt-get install -y -q '\''linux-headers-5.15.0-1027-gcp'\'''
+ local -r 'cmd=apt-get install -y -q '\''linux-headers-5.15.0-1027-gcp'\'''
+ (( i = 0 ))
+ (( i < 10 ))
+ eval 'apt-get install -y -q '\''linux-headers-5.15.0-1027-gcp'\'''
++ apt-get install -y -q linux-headers-5.15.0-1027-gcp
```

**Comment by jayadeep-jayaraman** [comment]
Hi @nvliyuan - apologies for the delay, unfortunately there is no option today to stop and start a cluster in an init script. Therefore I think we can ignore the tests for images which need this feature. In addition, it would be good to break out the scripts if in actual production environment users need to stop and start clusters midway, such that they can run the startup script , restart the cluster and if you add the ability of the script to run during reboot then the second part of the script can run.

File: spark-rapids/spark-rapids.sh [hunk 3]
```diff
@@ -57,15 +54,24 @@ readonly -A DEFAULT_NVIDIA_DEBIAN_CUDA_URLS=(
   [11.2]="${NVIDIA_BASE_DL_URL}/cuda/11.2.2/local_installers/cuda_11.2.2_460.32.03_linux.run"
   [11.5]="${NVIDIA_BASE_DL_URL}/cuda/11.5.2/local_installers/cuda_11.5.2_495.29.05_linux.run"
   [11.6]="${NVIDIA_BASE_DL_URL}/cuda/11.6.2/local_installers/cuda_11.6.2_510.47.03_linux.run"
-  [11.7]="${NVIDIA_BASE_DL_URL}/cuda/11.7.1/local_installers/cuda_11.7.1_515.65.01_linux.run")
+  [11.7]="${NVIDIA_BASE_DL_URL}/cuda/11.7.1/local_installers/cuda_11.7.1_515.65.01_linux.run"
+  [11.8]="${NVIDIA_BASE_DL_URL}/cuda/11.8.0/local_installers/cuda_11.8.0_520.61.05_linux.run")
 readonly DEFAULT_NVIDIA_DEBIAN_CUDA_URL=${DEFAULT_NVIDIA_DEBIAN_CUDA_URLS["${CUDA_VERSION}"]}
```
Comment (mengdong) [inline spark-rapids/spark-rapids.sh:59]: Could we also add support for CUDA 12.1?

File: spark-rapids/spark-rapids.sh [hunk 4]
```diff
@@ -180,23 +177,83 @@ function install_nvidia_gpu_driver() {
...
-      local -r cuda_package=cuda-toolkit-${CUDA_VERSION//./-}
-    else
-      local -r cuda_package=cuda-toolkit
+      if [[ -n "${CUDA_VERSION}" ]]; then
+        local -r cuda_package=cuda-toolkit-${CUDA_VERSION//./-}
+      else
+        local -r cuda_package=cuda-toolkit
+      fi
+      # Without --no-install-recommends this takes a very long time.
+      execute_with_retries "apt-get install -y -q --no-install-recommends cuda-drivers-${DEFAULT_NVIDIA_DEBIAN_GPU_DRIVER_VERSION_PREFIX}"
```
Comment (mengdong) [inline spark-rapids/spark-rapids.sh:254]: we can change this to ```execute_with_retries "apt-get install -y -q --no-install-recommends cuda-drivers```

**Comment by nvliyuan** [comment]
> Hi @nvliyuan - apologies for the delay, unfortunately there is no option today to stop and start a cluster in an init script. Therefore I think we can ignore the tests for images which need this feature. In addition, it would be good to break out the scripts if in actual production environment users need to stop and start clusters midway, such that they can run the startup script , restart the cluster and if you add the ability of the script to run during reboot then the second part of the script can run.

I skipped the test for the image which require reboot for this pr as a workaround. I will draft another pr to address the reboot issues and other comments.

File: spark-rapids/spark-rapids.sh (hunk 4 above)
Comment (nvliyuan) [reply spark-rapids/spark-rapids.sh:254]: Hi @mengdong , since spark-rapids has released for about two weeks, the release work is included in this pr, we need to merge it ASAP, I will draft another pr to address the comments and reboot issues.

**Review by jayadeep-jayaraman — APPROVED** [review]

**Comment by jayadeep-jayaraman** [comment]
Merged changes as tests have passed
